## Tensor Operations
1. Initialization of a Tensor
2. Tensor Mathematical Operations and Comparison
3. Tensor Indexing
4. Tensor Reshaping

In [2]:
import torch

# setup device
device = "cuda" if torch.cuda.is_available() else "cpu"


#### 1. Initialization of a Tensor

In [4]:
TENSOR = torch.tensor(
    [[1, 2, 3], [4, 5, 6]],  # 2x3 -> ixj ->  matrix tensor
    dtype=torch.float32,
    device=device,
    requires_grad=True,
)
TENSOR

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [11]:
print(f"""
Data type of the : {TENSOR.dtype}
Tensor running on Device : {TENSOR.device}
Shape of the tensor : {TENSOR.shape}
Requires gradient : {TENSOR.requires_grad}
""")


Data type of the : torch.float32
Tensor running on Device : cpu
Shape of the tensor : torch.Size([2, 3])
Requires gradient : True



In [48]:
torch.empty(size=(3, 3))

tensor([[8.3895e-07, 1.0499e-08, 2.1770e+23],
        [3.3854e-06, 2.6948e-09, 2.1571e-04],
        [1.3075e+22, 8.4481e+20, 2.6846e+23]])

In [82]:
# Normally distributed with mean=0, std=1
torch.empty(size=(3,3)).normal_(mean=0, std=1)

tensor([[ 0.6073,  1.7498,  1.1321],
        [-0.1008,  1.2326, -2.1597],
        [-0.0389,  0.0652,  1.8931]])

In [90]:
# Values from a unifrom with mean = 0 , std = 1
torch.empty(size=(3,3)).uniform_(0, 1)

tensor([[0.1747, 0.7354, 0.1525],
        [0.9686, 0.0062, 0.8218],
        [0.5831, 0.0482, 0.6620]])

In [15]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [38]:
torch.rand((3, 3))

tensor([[0.1716, 0.2119, 0.5953],
        [0.6969, 0.1642, 0.9029],
        [0.2735, 0.5712, 0.9579]])

In [49]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [94]:
# diagonal matrix of shape 3x3
torch.diag(torch.ones(3)) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [98]:
# Returns Identity Matrix
torch.eye(5, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [53]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

##### Tensors Conversion types (int , float, double)

In [106]:
TENSOR = torch.asarray(0)
TENSOR.bool()

tensor(False)

In [112]:
torch.asarray(5).short()

tensor(5, dtype=torch.int16)

In [113]:
torch.asarray(5).long()

tensor(5)

In [114]:
torch.asarray(5).half()

tensor(5., dtype=torch.float16)

In [115]:
torch.asarray(5).float()

tensor(5.)

In [116]:
torch.asarray(5).double()

tensor(5., dtype=torch.float64)

#### 2. Tensor Math & Comparison Operations

In [214]:
tensorx = torch.tensor([2, 3, 4])
tensory = torch.tensor([6, 7, 8])
tensorsq = torch.tensor([[2, 3], [4, 5]])
tensorz = torch.tensor([[2, 3, 6], [4, 5, 7]])


In [120]:
result = torch.empty(3)
torch.add(tensorx, tensory, out=result)
result

tensor([ 8., 10., 12.])

OR

In [224]:
print(tensorx, " + ",tensory , " = ",
torch.add(tensorx, tensory)
)

tensor([2, 3, 4])  +  tensor([6, 7, 8])  =  tensor([ 8, 10, 12])


OR

In [223]:
print(tensorx, " + ",tensory , " = ",
tensorx + tensory
)

tensor([2, 3, 4])  +  tensor([6, 7, 8])  =  tensor([ 8, 10, 12])


In [227]:
print(tensorx, " + ",tensory , " = ",
tensorx - tensory
)

tensor([12, 13, 14])  +  tensor([6, 7, 8])  =  tensor([6, 6, 6])


similaryly we can do for subtraction

In [226]:
tensorx += 10
tensorx

tensor([12, 13, 14])

In [229]:
print(tensorx, " ** ", 3 , " = ",
# tensory ** 3
# or
tensory.pow(3)
)

tensor([12, 13, 14])  **  3  =  tensor([216, 343, 512])


In [230]:
# Comparision operators
print(tensorx, " > ", 2 , " = ",
tensorx > 2
)

tensor([12, 13, 14])  >  2  =  tensor([True, True, True])


In [233]:
# Matrix Multiplicaton
# Note: ixj* ixj where j=i 
tensorA= torch.rand((2,4))
tensorB= torch.rand((4,10))

torch.mm(tensorA, tensorB)
# or 
tensorA.mm(tensorB)

tensor([[0.8904, 1.5446, 1.0064, 1.3534, 1.1505, 1.1668, 1.3180, 0.9426, 1.3507,
         1.1593],
        [0.8763, 1.5593, 1.1782, 0.7906, 0.7878, 0.8415, 0.9744, 1.0030, 1.0919,
         0.7814]])

In [190]:
# Matrix Exponentiation
# Note : Should be square matrix
torch.rand(3, 3).matrix_power(2)
# or
# torch.rand(2,2).matrix_exp()

tensor([[1.3518, 0.6861],
        [0.8502, 2.8143]])

In [207]:
# Element wise multiplication
print(tensorx,' * ',tensory, ' = ',
tensorx * tensory)

tensor([2, 3, 4])  *  tensor([6, 7, 8])  =  tensor([12, 21, 32])


In [208]:
# Dot product
print(tensorx, ' . ', tensory, ' = ',
torch.dot(tensorx, tensory))

tensor([2, 3, 4])  .  tensor([6, 7, 8])  =  tensor(65)


In [241]:
# Batch Matrix Multiplication
batch = 4
n = 2
m = 5
p = 12
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
tensor1

tensor([[[0.6057, 0.9586, 0.7390, 0.1205, 0.4363],
         [0.3813, 0.6776, 0.3843, 0.0784, 0.5051]],

        [[0.8485, 0.9057, 0.0611, 0.4336, 0.6424],
         [0.3522, 0.3533, 0.7019, 0.2427, 0.3840]],

        [[0.7337, 0.5231, 0.2446, 0.7969, 0.7134],
         [0.1580, 0.3225, 0.3091, 0.1240, 0.4364]],

        [[0.8576, 0.5357, 0.4475, 0.4940, 0.7672],
         [0.1862, 0.8382, 0.6166, 0.7913, 0.8192]]])

In [256]:
# Example of broadcasting
print(tensorsq," -  ", torch.ones((1, 2)), " = ",
tensorsq - torch.ones((1, 2))
)

tensor([[2, 3],
        [4, 5]])  -   tensor([[1., 1.]])  =  tensor([[1., 2.],
        [3., 4.]])


In [267]:
print(tensorsq," ** ", tensorsq, " = ",
tensorsq ** tensorsq
)

tensor([[2, 3],
        [4, 5]])  **  tensor([[2, 3],
        [4, 5]])  =  tensor([[   4,   27],
        [ 256, 3125]])


In [273]:
print(tensorx*-1, " = ",
torch.abs(tensorx*-1)
)

tensor([-12, -13, -14])  =  tensor([12, 13, 14])


In [280]:
print(tensorx, " max at index ",
torch.argmax(tensorx, dim=0)
)

tensor([12, 13, 14])  max at index  tensor(2)


In [281]:
print(tensorx, " mean =  ",
torch.mean(tensorx.float(), dim=0)
)

tensor([12, 13, 14])  mean =   tensor(13.)


In [290]:
print(tensorx, " sorted: ",
torch.sort(tensorx, dim=0, descending=True)
)

tensor([12, 13, 14])  sorted  torch.return_types.sort(
values=tensor([14, 13, 12]),
indices=tensor([2, 1, 0]))


#### 3. Tensor Indexing

In [295]:
tensorx

tensor([12, 13, 14])

In [293]:
# first feature
tensorx[0]

tensor(12)

In [ ]:
# last feature
tensorx[-1]

In [299]:
# assigning certain elements
tensorx[0] = 22
tensorx

tensor([22, 13, 14])

In [307]:
torch.where(tensorx == 22, 10000 , tensorx)

tensor([10000,    13,    14])

#### 4. Tensor Reshaping

In [308]:
torch.arange(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [309]:
torch.arange(9).view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [312]:
tensorA.reshape(2,2,2)

tensor([[[0.7222, 0.7921],
         [0.3346, 0.7652]],

        [[0.3517, 0.5942],
         [0.7795, 0.4338]]])

In [314]:
tensorA.t()

tensor([[0.7222, 0.3517],
        [0.7921, 0.5942],
        [0.3346, 0.7795],
        [0.7652, 0.4338]])

In [318]:
tensorx.view(3, -1)

tensor([[22],
        [13],
        [14]])

In [328]:
result = torch.chunk(tensorA, chunks = 2, dim=1)
result[0]

tensor([[0.7222, 0.7921],
        [0.3517, 0.5942]])

In [329]:
result[1]

tensor([[0.3346, 0.7652],
        [0.7795, 0.4338]])

In [336]:
result = torch.arange(9).unsqueeze(1)
print(result.shape)
result

torch.Size([9, 1])


tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [337]:
result = torch.arange(9).unsqueeze(1).unsqueeze(0)
print(result.shape)
result

torch.Size([1, 9, 1])


tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]])

In [8]:
40 % 100

40